### ISSUE TITLE
Hypersearch minimiz or close hotkey

### ISSUE THREAD

**Issue by ninja2bceen** [pietie/HyperSearch#1]
Pietie you are back! Thank you for considering it being open source though I have no idea what to do with that, someone smart will be able to help

The only thing I think is really missing is a way to minimize the search or a way to reopen the search if you closed it. Do you have time to allow for an additional hotkey option?

Tapatalk signature

**Comment by ninja2bceen** [comment]
Suggested hotkey to minimize the open app = 0

Suggested hotkey to maximize open app =tab

**Comment by pietie** [comment]
There has been a minimize key for a while now (MinimizeKey in the app.config). You can set this to whatever you want. To reopen you just hit your original trigger (e.g. F3).

Or is the issue that it is not working as expected?
