### ISSUE TITLE
remove input

### ISSUE THREAD

**Issue by ninja2bceen** [pietie/HyperSearch#10]
Within the input section, I'm unsure how to clear the content, I can certainly add more inputs but unclear how to remove the default

**Comment by pietie** [comment]
The default was setup with the DELETE button. Can you send me your Settings.json? Or just paste into http://pastebin.com/

**Comment by ninja2bceen** [comment]
{
  "General": {
    "HyperSpinPath": "E:\Arcade-PC\hyperspin",
    "RocketLauncherExePath": "E:\Arcade-PC\hyperspin\RocketLauncher\RocketLauncher.exe",
    "KeyboardType": 1,
    "SearchMode": 0,
    "CabMode": false,
    "HideMouseCursor": false,
    "StandAloneMode": false,
    "StandaloneWidth": 1600,
    "StandaloneHeight": 900,
    "BalloonToolTipTimeOutInMilliseconds": 0,
    "VerboseLogging": false
  },
  "Input": {
    "Triggers": {
      "Search": [
        92
      ],
      "SearchTriggerDelayInMilliseconds": 0,
      "Favourites": [
        93
      ],
      "FavouritesTriggerDelayInMilliseconds": 0,
      "Genre": [
        94
      ],
      "GenreTriggerDelayInMilliseconds": 0,
      "Settings": [
        99
      ],
      "SettingsTriggerDelayInMilliseconds": 0
    },
    "Up": [
      24
    ],
    "Right": [
      25
    ],
    "Down": [
      26
    ],
    "Left": [
      23
    ],
    "Action": [
      6
    ],
    "Back": [
      2
    ],
    "Clear": [
      32
    ],
    "Minimize": [
      146
    ],
    "Exit": [
      13,
      156
    ],
    "LayoutConfig": {
      "Name": "4 button NEO-GEO layout",
      "Description": null,
      "Buttons": [
        {
          "Position": 1,
          "HueOffset": 0.0
        },
        {
          "Position": 2,
          "HueOffset": 0.0
        },
        {
          "Position": 3,
          "HueOffset": 0.0
        },
        {
          "Position": 4,
          "HueOffset": 0.0
        }
      ]
    }
  },
  "Misc": {
    "EnableGameVideos": true,
    "ShowSystemImagesOnFilter": true,
    "ShowSystemImagesOnResults": true,
    "ShowWheelImagesOnResults": true,
    "AlternativeSystemWheelImagePath": null,
    "AlternativeGameWheelSourceFolder": null,
    "GenreWheelImageLocations": null
  }
}

**Comment by ninja2bceen** [comment]
say you want to go to input and remove the F3 function all together and you want it to only be G (totally making this up), you cant seem to remove f3 at all

**Comment by ninja2bceen** [comment]
this is now working for me. must press delete
