### ISSUE TITLE
launch hypersearch from wheel

### ISSUE THREAD

**Issue by ninja2bceen** [pietie/HyperSearch#14]
using parameter -search and the exe path in hyperhq, I only get a blank cmd prompt when trying to launch it within hyperspin

**Comment by ninja2bceen** [comment]
Preferably I would like to have a hypersearch wheel and have a subwheel for favorites search, genre search and regular search. Or there should be 3 buttons within hypersearch to press to search by x type within the ui if this can't be done. I think if the subwheel option can't be done having the ui buttons are a better option then three different keystrokes though I think that option is still important to have

**Comment by pietie** [comment]
Grab the latest release from https://github.com/pietie/HyperSearch/releases
Then, see https://github.com/pietie/HyperSearch/wiki/HyperSpin---Launching-from-a-wheel
