### ISSUE TITLE
exclude emulators

### ISSUE THREAD

**Issue by ghibu** [pietie/HyperSearch#16]
hi Pietie,

thanks for this awesome work!

Is there  a possibility to exclude  some emulators from the global search?
is there any command to do that?

Thanx!

**Comment by pietie** [comment]
No currently. Can I ask why you want to do this?

**Comment by ghibu** [comment]
Hi Pietie,

In fact i am using Your Hypersearch "plugin" and the HyperxmlSpin "plugin" from r0man0 :

I am using Your Hypersearch because  it is for me very easy to search any game  with the arcade stick on my cab in fullscreen.

I am using HyperXmlSpin to generate Favorite main game list (ex: i have for each kind of game a favorite cross-platform list by kind : racing / Flying/ Beat them Up etc....

The main issue whith Hypersearch is when i match my games the result display the game from each main system and also the same game from my favorite HyperXmlSpin list... But : 
i can't launch any game from these favorite HyperXmlSpin lists whithin Hypersearch.
Because to launch any game  Hyperseach need  the Path to the emulator and HyperXmlSpin doesn't have one. why? > it's because it's a cross platform list..   and so, hyperspin generate an error.

if we can exclude some emulators from hypersearch like here the hyperxmlspin list i have done.
there where only one occurence of the same game displayed and no error if someone launch a game from the displayed wheels.

(forgive my english because i am foreigner)
and thanks to pay attention to my request.

++

**Comment by pietie** [comment]
I am not familiar with HyperxmlSpin so can you perhaps provide me with an example with the files you're having trouble with? So a zip containing just the database/favourites related files causing issues.

**Comment by ghibu** [comment]
Ok, i am at work for now, soon as  i am at home i will forward you an example.
thank.

in fact as far as i know, in hyperlaunch there are ini.files containing rom path and emulators path.
But: for HyperXmlSpin these lines are blank. And  Hypersearch look into these files for include the request who must match.

**Comment by ghibu** [comment]
i can't put any zip archive here. don't know why... 
perhaps an email??

thanks  :)

**Comment by pietie** [comment]
You can either dropbox it or try uploading it to the HS forums ... not sure if they support something like that

**Comment by ghibu** [comment]
Hi there:
here is a link!

https://www.dropbox.com/s/226lrer9zc9juhd/ghibu_issue.7z?dl=0

leave me a feedback! 

thanks!     :)

**Comment by pietie** [comment]
Thanks for the files

Did you add the underscores in the folder names?

**Comment by pietie** [comment]
I don't yet understand how HyperSearch is picking those items up. Can you please http://pastebin.com/ your **Databases\Main Menu\Main Menu.xml**

The System names are read from there. So then does HyperxmlSpin write **Beat'em up** into Main Menu.xml?

**Comment by ghibu** [comment]
hi Pietie,
I am at work now. i can't pastebin.
But for  the question you asked me : i can tell you for sure it does! 
There are entries from HyperXmlSpin in the main menu xml. Each favorite list exist in this file.
If we can tell hypersearch to exclude them here.....

but keep in mind that the names of these favorites lists are created by me through hyperXmlSpin .
so they can have any name...

for the underscore in the name  i can say  you "no"

**Comment by pietie** [comment]
What's the benefit of having those in the Main Menu.xml then? I mean, how does HyperSpin handle those? How are they displayed in Hyperspin? Can you start them from HyperSpin?

I can add a config key to ignore certain Systems. It will have to be a "dumb" CSV list though, e.g. "SystemA, SystemB" etc

**Comment by pietie** [comment]
Okay update from this zip
https://dl.dropboxusercontent.com/u/59583314/HyperSearch%20IgnoreSystemCsv.7z

Edit your **Settings.json** file with notepad. Under the Misc section you can add the key **IgnoreSystemsCsv**

For example:

``` json
  "Misc": {
    "EnableGameVideos": true,
    "ShowSystemImagesOnFilter": true,
    "ShowSystemImagesOnResults": true,
    "ShowWheelImagesOnResults": true,
    "AlternativeSystemWheelImagePath": null,
    "AlternativeGameWheelSourceFolder": null,
    "GenreWheelImageLocations": null,
   "IgnoreSystemsCsv": "Nintendo 64, mame, Super Nintendo Entertainment System, Nintendo Entertainment System"
  }
```

**Comment by ghibu** [comment]
Great!

Thank You for that!! >  i'll try this soon as  i come back home and leave you a feedback.

-the benefit of having those in the Main Menu.xml is  that i can select the favorite multi-system list directly from the main menu.

-Yes  i can launch them the same way i launch any system

-They look like any other system in my main menu within hyperspin :D

in fact, it would be best if these lists could be launched in a sub-menu directly from à button, but I have not yet thought about how to do this. 

ghibu

**Comment by ghibu** [comment]
Hi!

i am sorry to bother you again but now i can't set up my hypersearch :

Here is the log:

 20:08:17  System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : key
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   à HyperSearch.MainWindow..ctor()
20:08:17  ERROR: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path 'Misc.IgnoreSystemsCsv', line 51, position 25.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.ReadInternal()
   à Newtonsoft.Json.JsonReader.ReadAsStringInternal()
   à Newtonsoft.Json.JsonTextReader.ReadAsString()
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   à HyperSearch.Classes.HyperSearchSettings.Load()

when i click on the setting button, whenever i click after , nothing happens : i can't select a path to hyperspin for example... and then the programm get stuck... oO ?

here is the line i add in the json file : 
"IgnoreSystemsCsv": Sports, pinball, Race games, flight games, shmups, Puzzle, plateform games, fight games, beat them up,

**Comment by pietie** [comment]
The values need to have quotes around them, see my example.

e.g. "Sports, pinball,......"

**Comment by ghibu** [comment]
Ho! Yes!  My mistake!  

It work perfectly!!!!

 I don't know if it could serve anyone else but thank you, and i really like this plugin!

Bye

ghibu
