### ISSUE TITLE
Videos not being played in search results

### ISSUE THREAD

**Issue by Kondorito** [pietie/HyperSearch#17]
Hey pietie! What's up!
The videos are not showing with the results (I am using the Beta 2 version). 
My log files says (for example with 19XX):

17:28:08  Video failed: file:///C:/Hyperspin/Media/MAME/Video/19xx.flv, with error: System.IO.FileNotFoundException: Error downloading multimedia file. ---> System.Runtime.InteropServices.COMException (0xC00D0FEA): Excepción de HRESULT: 0xC00D0FEA 

But if I do a double-click on that link, or even go to the path, the video is there (and it reproduces fine in Hyperspin).

Let me know if more info is required.

Thanks!

**Comment by Kondorito** [comment]
I just finished testing it with mp4 videos and they are being previewed, so it seems the issue happens with flvs.

**Comment by pietie** [comment]
Correct, it is a codec issue with FLVs. You can try looking around for an FLV codec. I still want to build MP4 conversion into the app. HyperSpin supports it so we really need to get rid of the FLVs.

**Comment by Kondorito** [comment]
Agreed.
I am updating my video library to MP4, so even though FLVs gives this error, we can disregard this issue for now. Thanks pietie.
