### ISSUE TITLE
Focus issue

### ISSUE THREAD

**Issue by ninja2bceen** [pietie/HyperSearch#3]
When you launch hypersearch with hyperspin running on Windows 7 with 1900x1080 resultion, the app doesn't always come up. If you have hyperspin minimized it always domes up

**Comment by pietie** [comment]
I've not had any more reports of this so I'm considering this closed for now.

**Comment by ninja2bceen** [comment]
this is still not working for me. I see in the log that HS is not an active window but it is :D

**Comment by ninja2bceen** [comment]
I just grabbed the version in beta 2. Hq has the exe file path, parameter is -search. When I try opening the wheel is just get a blank command prompt
