### ISSUE TITLE
Make favorite and genre search a button 

### ISSUE THREAD

**Issue by ninja2bceen** [pietie/HyperSearch#4]
The minimize feature was giving me problems if I decided I wanted another type of search. To mitigate this, having the regular search upon starting is ideal. Then within the keyboard, add a button to search favorites and search genres so that it's all in the ui

**Comment by pietie** [comment]
You can just switch between the different search screens using the different trigger keys.
Let's see how it goes for you with the next release..hopefully the minimize works correctly then.

**Comment by ninja2bceen** [comment]
I was thinking more around if you were to add it to the main menu wheel. maybe I make a subwheel, one for each search when that is working
