### ISSUE TITLE
Add ability to run exe on a hyperspin wheel

### ISSUE THREAD

**Issue by ninja2bceen** [pietie/HyperSearch#5]
The hot keys are great but making this more cabinet friendly, a hyperspin wheel to launch the app is a better experience. I think both the hotkey and wheel option should exist.

**Comment by pietie** [comment]
Ah I think I understand. 
So maybe we can provide CLI options like 

  HyperSearch.exe -genre 

To bring up the Genre search. You can then setup your wheel however you like.

**Comment by mccorkled** [comment]
I have Search to boot on HS launch. I mapped a key on my 360 controller to "F12" to open the search. I think since I load Search on start the CLI options are not working. I also have a Search main menu wheel and when I click it, I just get a CMD screen that sits there doing nothing.

**Comment by pietie** [comment]
Can you post your full log please?

**Comment by mccorkled** [comment]
[HyperSearchLog.txt](https://github.com/pietie/HyperSearch/files/1748189/HyperSearchLog.txt)

Thank you

**Comment by pietie** [comment]
I don't see anything obvious in the log. If you send me your Settings.json file I'll try and reproduce it. Send me your HS launch settings as well. 

How is the Search wheel setup?

**Comment by mccorkled** [comment]
Search.ini
https://pastebin.com/p9G52tbw

Settings.json
https://pastebin.com/jME0TQ6m

I have the wheel setup on the main menu. I set it to exe within HyperHQ. 
Thanks.

**Comment by pietie** [comment]
You need a hyphen in front of _search_


```ini
[exe info]
path=....
exe=HyperSearch.exe
parameters=-search
pcgame=true
winstate=HIDDEN
hyperlaunch=false
```

**Comment by mccorkled** [comment]
Thank you. I had one there but it must have been the wrong one.
