### ISSUE TITLE
Allow for easy ui to adjust art,font colors

### ISSUE THREAD

**Issue by ninja2bceen** [pietie/HyperSearch#6]
Someone create a nice font, color, template for the keyboard and results for your app. To get really creative stuff and good looking stuff, maybe within the settings ui you are making, it could have a ui to adjust formatting of the window

**Comment by pietie** [comment]
Thanks for the suggestion but I think that would be too much work for too little reward. There are already tools out there to assist with XAML editting (e.g. KAXAML) and really...if you can figure out how to setup Hyperspin you can figure out how to change a couple of basic styles in XAML with a bit of RTFM :)
